version: '3.8'

services:
  inference-service:
    build: .
    image: cats-dogs-classifier:latest
    ports:
      - "8000:8000"
    volumes:
      - ./model.pth:/app/model.pth:ro
    restart: always
